# Generated by Django 5.2.6 on 2025-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('streak_days', models.IntegerField(default=0, verbose_name='Streak days')),
                ('level', models.IntegerField(default=0, verbose_name='User level')),
                ('interests', models.JSONField(blank=True, default=dict, verbose_name='User interests')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profile picture')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='User biography')),
                ('user_time_zone', models.CharField(blank=True, max_length=255, null=True, verbose_name='User timezone')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Last active timestamp')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='Authentication token')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-id'],
            },
        ),
    ]
