# Generated by Django 5.2.6 on 2025-09-12 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_usermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated timestamp'),
        ),
    ]
