# Generated by Django 5.2.6 on 2025-09-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_usermodel_created_usermodel_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Coins balance'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='diamonds',
            field=models.IntegerField(default=0, verbose_name='Diamonds balance'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='User link'),
        ),
    ]
