# Generated by Django 5.2.6 on 2025-09-15 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_auth', '0004_usermodel_coins_usermodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveawayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название розыгрыша')),
                ('description', models.TextField(verbose_name='Описание розыгрыша')),
                ('prize_fond', models.PositiveIntegerField(verbose_name='Сумма приза')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала розыгрыша')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания розыгрыша')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('giveaway_cost', models.PositiveIntegerField(verbose_name='Стоимость участия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveaways', to='api_auth.usermodel')),
                ('participants', models.ManyToManyField(related_name='participated_giveaways', to='api_auth.usermodel')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_giveaways', to='api_auth.usermodel')),
            ],
            options={
                'verbose_name': 'Giveaway',
                'verbose_name_plural': 'Giveaways',
                'ordering': ['-start_date'],
            },
        ),
    ]
