# Generated by Django 5.2.6 on 2025-09-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamedification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveawaymodel',
            name='collected_funds',
            field=models.PositiveIntegerField(default=0, verbose_name='Собранные средства от участников'),
        ),
    ]
